name: build and test 
on:
  push:

jobs:

 build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: install frontend dependencies 
        run : npm ci
        working-directory: ./client

      - name: install frontend test 
        run : npm test
        working-directory: ./client

      - name: install backend dependencies
        run : npm ci
        working-directory: ./server

      - name: install backend test
        run : npm test 
        working-directory: ./server




      