name: CI
on:
  push:

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml

  docker-build-and-push:
    needs: build
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  deploy:
      needs: docker-build-and-push
      uses: ./.github/workflows/cd.yml
      secrets: inherit
  
